### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]'

### ISSUE THREAD

**Issue by iamsarath1986** [opdahlmann/ng2-opd-popup-sample#6]
I am using angular 4. I have tried to integrate this but I am getting error. 

Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:63531:34)
    at http://localhost:4200/vendor.bundle.js:76485:44
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:76468:49)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:87621:66)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:87580:52)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:87542:23)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:93440:25)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:93426:21)
    at Object.../../../../../src/main.ts (http://localhost:4200/main.bundle.js:510:124)
syntaxError @ compiler.es5.js:1540
(anonymous) @ compiler.es5.js:14494
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:14477
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules @ compiler.es5.js:25630
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents @ compiler.es5.js:25589
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync @ compiler.es5.js:25551
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4811
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4797
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap d3b6771…:54
3 @ main.ts:11
__webpack_require__ @ bootstrap d3b6771…:54
webpackJsonpCallback @ bootstrap d3b6771…:25
(anonymous) @ main.bundle.js:1

**Comment by lianesten** [comment]
+1

**Comment by f22hd** [comment]
the same issue

**Comment by SerdarNur** [comment]
@opdahlmann the error still exists !!!!!

**Comment by mastrauckas** [comment]
I'm having this issue too.  Has anyone found a workaround yet?

@opdahlmann where is the code for `ng2-opd-popup` so someone can fix it for `Aungular 4` and create Pull Request?

**Comment by mastrauckas** [comment]
@opdahlmann Where is the code to the popup so someone can fix it?

**Comment by hunterctzl** [comment]
same problem. Does anyone have an answer?

**Comment by mastrauckas** [comment]
Anyone know where the repository for this library is?

**Comment by CayetanoHerreraLuisRicardo** [comment]
I have the some problem

**ng -v**

angular/cli: 1.4.5
node: 6.11.4
os: win32 x64
angular/animations: 4.4.6
angular/common: 4.4.6
angular/compiler: 4.4.6
angular/core: 4.4.6
angular/forms: 4.4.6
angular/http: 4.4.6
angular/platform-browser: 4.4.6
angular/platform-browser-dynamic: 4.4.6
angular/router: 4.4.6
angular/cli: 1.4.5
angular/compiler-cli: 4.4.6
angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by MohammedYaseen** [comment]
the same issue:

Angular CLI: 1.5.0
Node: 8.9.1
OS: darwin x64

**Comment by ShiruJan** [comment]
Inside the folder node_modules/ng2-opd-popup, there is a folder called "node_modules", delete it, after recompiling the project works fine. It works for me, I use Angular5.

**Comment by jfaquinojr** [comment]
same issue
dotnet new angular

Node: 7.10.1


        "@angular/animations": "4.2.5",
        "@angular/common": "4.2.5",
        "@angular/compiler": "4.2.5",
        "@angular/compiler-cli": "4.2.5",
        "@angular/core": "4.2.5",
        "@angular/forms": "4.2.5",
        "@angular/http": "4.2.5",
        "@angular/platform-browser": "4.2.5",
        "@angular/platform-browser-dynamic": "4.2.5",
        "@angular/platform-server": "4.2.5",
        "@angular/router": "4.2.5",
        "@ngtools/webpack": "1.5.0",
        "@types/webpack-env": "1.13.0",
        "angular2-template-loader": "0.6.2",
        "aspnet-prerendering": "^3.0.1",
        "aspnet-webpack": "^2.0.1",
        "awesome-typescript-loader": "3.2.1",
        "bootstrap": "3.3.7",
        "css": "2.2.1",
        "css-loader": "0.28.4",
        "es6-shim": "0.35.3",
        "event-source-polyfill": "0.0.9",
        "expose-loader": "0.7.3",
        "extract-text-webpack-plugin": "2.1.2",
        "file-loader": "0.11.2",
        "html-loader": "0.4.5",
        "isomorphic-fetch": "2.2.1",
        "jquery": "3.2.1",
        "json-loader": "0.5.4",
        "ng2-opd-popup": "^1.1.21",
        "preboot": "4.5.2",
        "raw-loader": "0.5.1",
        "reflect-metadata": "0.1.10",
        "rxjs": "5.5.2",
        "style-loader": "0.18.2",
        "to-string-loader": "1.1.5",
        "typescript": "2.4.1",
        "url-loader": "0.5.9",
        "webpack": "2.5.1",
        "webpack-hot-middleware": "2.18.2",
        "webpack-merge": "4.1.0",
        "zone.js": "0.8.12"
